from __future__ import annotations

from typing import Protocol, runtime_checkable

from framework.common.page.schemas.page_result import PageResult
from module_system.controller.admin.tenant.vo.tenant.tenant_page_req_vo import TenantPageReqVO
from module_system.dal.dataobject.tenant.tenant_do import TenantDO


@runtime_checkable
class TenantService(Protocol):
    async def get_tenant_id_list(self, include_disabled: bool = False) -> list[int]: ...

    async def update_status(self, tenant_id: int, status: int) -> None: ...

    async def delete_tenant(self, id: int) -> None: ...

    async def delete_tenant_batch(self, ids: list[int]) -> int: ...

    async def get_tenant(self, id: int) -> TenantDO: ...

    async def get_tenant_page(self, page_req_vo: TenantPageReqVO) -> PageResult[TenantDO]: ...

    async def get_tenant_list_by_status(self, status: int) -> list[TenantDO]: ...

    async def get_tenant_by_name(self, name: str) -> TenantDO: ...

    async def get_tenant_by_website(self, website: str) -> TenantDO: ...

    async def get_tenant_count_by_package_id(self, package_id: int) -> int: ...

    async def get_tenant_list_by_package_id(self, package_id: int) -> list[TenantDO]: ...

    async def create_tenant(self, create_req_vo): ...

    async def update_tenant(self, update_req_vo): ...

    async def update_tenant_role_menu(self, tenant_id, menu_ids): ...

    async def handle_tenant_info(self, handler): ...

    async def handle_tenant_menu(self, handler): ...

    async def valid_tenant(self, id): ...

    async def tenant_info(self, tenant_id): ...

    async def authorize_session(self, identity, policy): ...

    async def authorize_workload(self, identity, capability): ...

    async def enabled_tenant_ids(self): ...
