from fastapi import APIRouter

from module_system.controller.admin.announcement.announcement_controller import (
    announcement_controller,
)
from module_system.controller.admin.area.area_controller import area_controller
from module_system.controller.admin.auth.auth_controller import auth_controller
from module_system.controller.admin.auth.qr_login_controller import qr_login_controller
from module_system.controller.admin.captcha.captcha_controller import captcha_controller
from module_system.controller.admin.dept.dept_controller import dept_controller
from module_system.controller.admin.dept.post_controller import post_controller
from module_system.controller.admin.dict.dict_data_controller import dict_data_controller
from module_system.controller.admin.dict.dict_type_controller import dict_type_controller
from module_system.controller.admin.logger.login_log_controller import login_log_controller
from module_system.controller.admin.logger.operate_log_controller import (
    operate_log_controller,
)
from module_system.controller.admin.mail.mail_account_controller import mail_account_controller
from module_system.controller.admin.mail.mail_log_controller import mail_log_controller
from module_system.controller.admin.mail.mail_template_controller import mail_template_controller
from module_system.controller.admin.notification.notice_controller import (
    notice_controller,
)
from module_system.controller.admin.notification.notice_log_controller import (
    notice_log_controller,
)
from module_system.controller.admin.notification.notice_message_controller import (
    notice_message_controller,
)
from module_system.controller.admin.oauth2.oauth2_client_controller import oauth2_client_controller
from module_system.controller.admin.oauth2.oauth2_open_controller import oauth2_open_controller
from module_system.controller.admin.oauth2.oauth2_token_controller import oauth2_token_controller
from module_system.controller.admin.oauth2.oauth2_user_controller import oauth2_user_controller
from module_system.controller.admin.permission.menu_controller import menu_controller
from module_system.controller.admin.permission.permission_controller import permission_controller
from module_system.controller.admin.permission.role_controller import role_controller
from module_system.controller.admin.sms.sms_callback_controller import sms_callback_controller
from module_system.controller.admin.sms.sms_channel_controller import sms_channel_controller
from module_system.controller.admin.sms.sms_log_controller import sms_log_controller
from module_system.controller.admin.sms.sms_template_controller import sms_template_controller
from module_system.controller.admin.social.social_client_controller import social_client_controller
from module_system.controller.admin.social.social_user_controller import social_user_controller
from module_system.controller.admin.tenant.tenant_controller import tenant_controller
from module_system.controller.admin.tenant.tenant_package_controller import (
    tenant_package_controller,
)
from module_system.controller.admin.user.user_controller import user_controller
from module_system.controller.admin.user.user_profile_controller import user_profile_controller

# 创建Admin端二级路由器
admin_router = APIRouter()

# 包含三级路由（控制器）
admin_router.include_router(area_controller)
admin_router.include_router(auth_controller)
admin_router.include_router(qr_login_controller)
admin_router.include_router(captcha_controller)
admin_router.include_router(dept_controller)
admin_router.include_router(post_controller)
admin_router.include_router(dict_type_controller)
admin_router.include_router(dict_data_controller)
admin_router.include_router(login_log_controller)
admin_router.include_router(mail_account_controller)
admin_router.include_router(mail_log_controller)
admin_router.include_router(mail_template_controller)
admin_router.include_router(menu_controller)
admin_router.include_router(notice_controller)
admin_router.include_router(announcement_controller)
admin_router.include_router(notice_message_controller)
admin_router.include_router(notice_log_controller)
admin_router.include_router(oauth2_client_controller)
admin_router.include_router(oauth2_token_controller)
admin_router.include_router(oauth2_open_controller)
admin_router.include_router(oauth2_user_controller)
admin_router.include_router(operate_log_controller)
admin_router.include_router(permission_controller)
admin_router.include_router(role_controller)
admin_router.include_router(sms_callback_controller)
admin_router.include_router(sms_channel_controller)
admin_router.include_router(sms_log_controller)
admin_router.include_router(sms_template_controller)
admin_router.include_router(social_client_controller)
admin_router.include_router(social_user_controller)
admin_router.include_router(tenant_controller)
admin_router.include_router(tenant_package_controller)
admin_router.include_router(user_controller)
admin_router.include_router(user_profile_controller)
