-- module_system 建表脚本
-- 数据库方言：kingbase
-- 本文件由模型导出生成，请勿手工修改；表结构变更请改模型后重新导出。


-- system_announcement：公告表
CREATE TABLE system_announcement (
	title VARCHAR(100) NOT NULL, 
	content TEXT NOT NULL, 
	status SMALLINT NOT NULL, 
	is_top BOOLEAN NOT NULL, 
	sort INTEGER NOT NULL, 
	category SMALLINT NOT NULL, 
	publish_time TIMESTAMP WITHOUT TIME ZONE, 
	expire_time TIMESTAMP WITHOUT TIME ZONE, 
	publisher VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_system_announcement_tenant ON system_announcement (tenant_id);
COMMENT ON TABLE system_announcement IS '公告表';
COMMENT ON COLUMN system_announcement.title IS '公告标题';
COMMENT ON COLUMN system_announcement.content IS '公告内容';
COMMENT ON COLUMN system_announcement.status IS '公告状态（0-草稿，1-待发布，2-已发布，3-已过期）';
COMMENT ON COLUMN system_announcement.is_top IS '是否置顶';
COMMENT ON COLUMN system_announcement.sort IS '排序序号（数值越小越靠前）';
COMMENT ON COLUMN system_announcement.category IS '公告类别，参见 AnnouncementCategoryEnum';
COMMENT ON COLUMN system_announcement.publish_time IS '发布时间';
COMMENT ON COLUMN system_announcement.expire_time IS '过期时间';
COMMENT ON COLUMN system_announcement.publisher IS '发布人';
COMMENT ON COLUMN system_announcement.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_announcement.id IS '主键 ID';
COMMENT ON COLUMN system_announcement.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_announcement.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_announcement.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_announcement.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_announcement.deleted IS '是否已删除';


-- system_authorization_revision：系统授权版本
CREATE TABLE system_authorization_revision (
	revision BIGINT NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
COMMENT ON TABLE system_authorization_revision IS '系统授权版本';
COMMENT ON COLUMN system_authorization_revision.id IS '主键 ID';
COMMENT ON COLUMN system_authorization_revision.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_authorization_revision.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_authorization_revision.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_authorization_revision.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_authorization_revision.deleted IS '是否已删除';


-- system_dept：部门信息表
CREATE TABLE system_dept (
	name VARCHAR(30) NOT NULL, 
	parent_id BIGINT NOT NULL, 
	sort INTEGER NOT NULL, 
	leader_user_id BIGINT, 
	phone VARCHAR(11), 
	email VARCHAR(50), 
	status SMALLINT NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_dept_tenant_id UNIQUE (tenant_id, id)
);
CREATE INDEX ix_system_dept_tenant ON system_dept (tenant_id);
COMMENT ON TABLE system_dept IS '部门信息表';
COMMENT ON COLUMN system_dept.name IS '部门名称';
COMMENT ON COLUMN system_dept.parent_id IS '父部门id';
COMMENT ON COLUMN system_dept.sort IS '显示顺序';
COMMENT ON COLUMN system_dept.leader_user_id IS '负责人';
COMMENT ON COLUMN system_dept.phone IS '联系电话';
COMMENT ON COLUMN system_dept.email IS '邮箱';
COMMENT ON COLUMN system_dept.status IS '开启状态（1-启用，0-禁用）【StatusEnum】';
COMMENT ON COLUMN system_dept.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_dept.id IS '主键 ID';
COMMENT ON COLUMN system_dept.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_dept.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_dept.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_dept.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_dept.deleted IS '是否已删除';


-- system_dict_data：字典数据表
CREATE TABLE system_dict_data (
	sort INTEGER NOT NULL, 
	label VARCHAR(100) NOT NULL, 
	value VARCHAR(100) NOT NULL, 
	dict_type VARCHAR(100) NOT NULL, 
	status SMALLINT NOT NULL, 
	color_type VARCHAR(100), 
	tag_style JSON, 
	permission VARCHAR(100), 
	remark VARCHAR(500), 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_dict_data_active_0 UNIQUE (dict_type, value, active_key)
);
COMMENT ON TABLE system_dict_data IS '字典数据表';
COMMENT ON COLUMN system_dict_data.sort IS '字典排序';
COMMENT ON COLUMN system_dict_data.label IS '字典标签';
COMMENT ON COLUMN system_dict_data.value IS '字典键值';
COMMENT ON COLUMN system_dict_data.dict_type IS '字典类型';
COMMENT ON COLUMN system_dict_data.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_dict_data.color_type IS '颜色类型';
COMMENT ON COLUMN system_dict_data.tag_style IS '按钮样式';
COMMENT ON COLUMN system_dict_data.permission IS '权限标识（该选项所需的权限码，NULL表示无需权限）';
COMMENT ON COLUMN system_dict_data.remark IS '备注';
COMMENT ON COLUMN system_dict_data.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_dict_data.id IS '主键 ID';
COMMENT ON COLUMN system_dict_data.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_dict_data.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_dict_data.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_dict_data.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_dict_data.deleted IS '是否已删除';


-- system_dict_type：字典类型表
CREATE TABLE system_dict_type (
	name VARCHAR(100) NOT NULL, 
	type VARCHAR(100) NOT NULL, 
	status SMALLINT NOT NULL, 
	remark VARCHAR(500), 
	deleted_time TIMESTAMP WITHOUT TIME ZONE, 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_dict_type_active_0 UNIQUE (name, active_key), 
	CONSTRAINT uq_system_dict_type_active_1 UNIQUE (type, active_key)
);
COMMENT ON TABLE system_dict_type IS '字典类型表';
COMMENT ON COLUMN system_dict_type.name IS '字典名称';
COMMENT ON COLUMN system_dict_type.type IS '字典类型';
COMMENT ON COLUMN system_dict_type.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_dict_type.remark IS '备注';
COMMENT ON COLUMN system_dict_type.deleted_time IS '删除时间';
COMMENT ON COLUMN system_dict_type.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_dict_type.id IS '主键 ID';
COMMENT ON COLUMN system_dict_type.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_dict_type.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_dict_type.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_dict_type.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_dict_type.deleted IS '是否已删除';


-- system_login_log：系统访问记录
CREATE TABLE system_login_log (
	log_type SMALLINT NOT NULL, 
	trace_id VARCHAR(64) NOT NULL, 
	user_id BIGINT NOT NULL, 
	user_type SMALLINT NOT NULL, 
	username VARCHAR(50) NOT NULL, 
	result SMALLINT NOT NULL, 
	user_ip VARCHAR(50) NOT NULL, 
	user_agent VARCHAR(512) NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_system_login_log_tenant ON system_login_log (tenant_id);
COMMENT ON TABLE system_login_log IS '系统访问记录';
COMMENT ON COLUMN system_login_log.log_type IS '日志类型（枚举）【LoginLogTypeEnum】';
COMMENT ON COLUMN system_login_log.trace_id IS '链路追踪编号';
COMMENT ON COLUMN system_login_log.user_id IS '用户编号';
COMMENT ON COLUMN system_login_log.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_login_log.username IS '用户账号';
COMMENT ON COLUMN system_login_log.result IS '登录结果（枚举）【LoggerLoginResultEnum】';
COMMENT ON COLUMN system_login_log.user_ip IS '用户IP';
COMMENT ON COLUMN system_login_log.user_agent IS '浏览器UA';
COMMENT ON COLUMN system_login_log.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_login_log.id IS '主键 ID';
COMMENT ON COLUMN system_login_log.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_login_log.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_login_log.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_login_log.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_login_log.deleted IS '是否已删除';


-- system_mail_account：邮箱账号表
CREATE TABLE system_mail_account (
	mail VARCHAR(255) NOT NULL, 
	username VARCHAR(255) NOT NULL, 
	password VARCHAR(255) NOT NULL, 
	host VARCHAR(255) NOT NULL, 
	port INTEGER NOT NULL, 
	ssl_enable BOOLEAN NOT NULL, 
	starttls_enable BOOLEAN NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
COMMENT ON TABLE system_mail_account IS '邮箱账号表';
COMMENT ON COLUMN system_mail_account.mail IS '邮箱';
COMMENT ON COLUMN system_mail_account.username IS '用户名';
COMMENT ON COLUMN system_mail_account.password IS '密码';
COMMENT ON COLUMN system_mail_account.host IS 'SMTP 服务器域名';
COMMENT ON COLUMN system_mail_account.port IS 'SMTP 服务器端口';
COMMENT ON COLUMN system_mail_account.ssl_enable IS '是否开启 SSL';
COMMENT ON COLUMN system_mail_account.starttls_enable IS '是否开启 STARTTLS';
COMMENT ON COLUMN system_mail_account.id IS '主键 ID';
COMMENT ON COLUMN system_mail_account.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_mail_account.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_mail_account.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_mail_account.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_mail_account.deleted IS '是否已删除';


-- system_mail_log：邮件日志表
CREATE TABLE system_mail_log (
	user_id BIGINT, 
	user_type SMALLINT NOT NULL, 
	to_mail TEXT NOT NULL, 
	cc_mail TEXT, 
	bcc_mail TEXT, 
	account_id BIGINT NOT NULL, 
	from_mail VARCHAR(255) NOT NULL, 
	template_id BIGINT NOT NULL, 
	template_code VARCHAR(63) NOT NULL, 
	template_nickname VARCHAR(255), 
	template_title VARCHAR(255) NOT NULL, 
	template_content TEXT NOT NULL, 
	template_params JSON NOT NULL, 
	send_status SMALLINT NOT NULL, 
	send_time TIMESTAMP WITHOUT TIME ZONE, 
	send_message_id VARCHAR(255), 
	send_exception TEXT, 
	send_claim_token VARCHAR(32), 
	send_claim_until TIMESTAMP WITHOUT TIME ZONE, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
COMMENT ON TABLE system_mail_log IS '邮件日志表';
COMMENT ON COLUMN system_mail_log.user_id IS '用户编号';
COMMENT ON COLUMN system_mail_log.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_mail_log.to_mail IS '接收邮箱地址(多个逗号分隔)';
COMMENT ON COLUMN system_mail_log.cc_mail IS '抄送邮箱地址(多个逗号分隔)';
COMMENT ON COLUMN system_mail_log.bcc_mail IS '密送邮箱地址(多个逗号分隔)';
COMMENT ON COLUMN system_mail_log.account_id IS '邮箱账号编号';
COMMENT ON COLUMN system_mail_log.from_mail IS '发送邮箱地址';
COMMENT ON COLUMN system_mail_log.template_id IS '模板编号';
COMMENT ON COLUMN system_mail_log.template_code IS '模板编码';
COMMENT ON COLUMN system_mail_log.template_nickname IS '模版发送人名称';
COMMENT ON COLUMN system_mail_log.template_title IS '邮件标题';
COMMENT ON COLUMN system_mail_log.template_content IS '邮件内容';
COMMENT ON COLUMN system_mail_log.template_params IS '邮件参数';
COMMENT ON COLUMN system_mail_log.send_status IS '发送状态【MailSendStatusEnum】';
COMMENT ON COLUMN system_mail_log.send_time IS '发送时间';
COMMENT ON COLUMN system_mail_log.send_message_id IS '发送返回的消息 ID';
COMMENT ON COLUMN system_mail_log.send_exception IS '发送异常';
COMMENT ON COLUMN system_mail_log.send_claim_token IS '外发 claim 令牌';
COMMENT ON COLUMN system_mail_log.send_claim_until IS '外发前 claim 到期时间';
COMMENT ON COLUMN system_mail_log.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_mail_log.id IS '主键 ID';
COMMENT ON COLUMN system_mail_log.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_mail_log.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_mail_log.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_mail_log.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_mail_log.deleted IS '是否已删除';


-- system_mail_template：邮件模版表
CREATE TABLE system_mail_template (
	name VARCHAR(63) NOT NULL, 
	code VARCHAR(63) NOT NULL, 
	account_id BIGINT NOT NULL, 
	nickname VARCHAR(255), 
	title VARCHAR(255) NOT NULL, 
	content TEXT NOT NULL, 
	params JSON NOT NULL, 
	status SMALLINT NOT NULL, 
	remark VARCHAR(255), 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
COMMENT ON TABLE system_mail_template IS '邮件模版表';
COMMENT ON COLUMN system_mail_template.name IS '模板名称';
COMMENT ON COLUMN system_mail_template.code IS '模板编码';
COMMENT ON COLUMN system_mail_template.account_id IS '发送的邮箱账号编号';
COMMENT ON COLUMN system_mail_template.nickname IS '发送人名称';
COMMENT ON COLUMN system_mail_template.title IS '模板标题';
COMMENT ON COLUMN system_mail_template.content IS '模板内容';
COMMENT ON COLUMN system_mail_template.params IS '参数数组';
COMMENT ON COLUMN system_mail_template.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_mail_template.remark IS '备注';
COMMENT ON COLUMN system_mail_template.id IS '主键 ID';
COMMENT ON COLUMN system_mail_template.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_mail_template.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_mail_template.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_mail_template.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_mail_template.deleted IS '是否已删除';


-- system_menu：菜单权限表
CREATE TABLE system_menu (
	name VARCHAR(50) NOT NULL, 
	permission VARCHAR(100) NOT NULL, 
	kind VARCHAR(16) NOT NULL, 
	data_permission BOOLEAN NOT NULL, 
	url VARCHAR(2048), 
	sort INTEGER NOT NULL, 
	parent_id BIGINT NOT NULL, 
	path VARCHAR(200) NOT NULL, 
	icon VARCHAR(100) NOT NULL, 
	component VARCHAR(255), 
	component_name VARCHAR(255), 
	status SMALLINT NOT NULL, 
	visible BOOLEAN NOT NULL, 
	keep_alive BOOLEAN NOT NULL, 
	always_show BOOLEAN NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
COMMENT ON TABLE system_menu IS '菜单权限表';
COMMENT ON COLUMN system_menu.name IS '菜单名称';
COMMENT ON COLUMN system_menu.permission IS '权限标识';
COMMENT ON COLUMN system_menu.kind IS '菜单种类：group/page/action/link/iframe';
COMMENT ON COLUMN system_menu.data_permission IS '是否为数据权限操作，承接源 DATA 类型';
COMMENT ON COLUMN system_menu.url IS '外链或内嵌页面地址';
COMMENT ON COLUMN system_menu.sort IS '显示顺序';
COMMENT ON COLUMN system_menu.parent_id IS '父菜单ID';
COMMENT ON COLUMN system_menu.path IS '路由地址';
COMMENT ON COLUMN system_menu.icon IS '菜单图标';
COMMENT ON COLUMN system_menu.component IS '组件路径';
COMMENT ON COLUMN system_menu.component_name IS '组件名';
COMMENT ON COLUMN system_menu.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_menu.visible IS '是否可见';
COMMENT ON COLUMN system_menu.keep_alive IS '是否缓存';
COMMENT ON COLUMN system_menu.always_show IS '是否总是显示';
COMMENT ON COLUMN system_menu.id IS '主键 ID';
COMMENT ON COLUMN system_menu.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_menu.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_menu.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_menu.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_menu.deleted IS '是否已删除';


-- system_notification_message：站内信消息表
CREATE TABLE system_notification_message (
	user_id BIGINT NOT NULL, 
	user_type SMALLINT NOT NULL, 
	notice_id BIGINT NOT NULL, 
	notice_log_id BIGINT, 
	notice_title VARCHAR(100) NOT NULL, 
	notice_content TEXT NOT NULL, 
	notice_type INTEGER NOT NULL, 
	publisher_info JSON, 
	sent_channels JSON NOT NULL, 
	read_status BOOLEAN NOT NULL, 
	read_time TIMESTAMP WITHOUT TIME ZONE, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_system_notification_message_tenant ON system_notification_message (tenant_id);
COMMENT ON TABLE system_notification_message IS '站内信消息表';
COMMENT ON COLUMN system_notification_message.user_id IS '用户id';
COMMENT ON COLUMN system_notification_message.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_notification_message.notice_id IS '关联的通知编号';
COMMENT ON COLUMN system_notification_message.notice_log_id IS '通知日志ID (system_notification_notice_log.id)';
COMMENT ON COLUMN system_notification_message.notice_title IS '通知标题';
COMMENT ON COLUMN system_notification_message.notice_content IS '通知内容';
COMMENT ON COLUMN system_notification_message.notice_type IS '通知类型';
COMMENT ON COLUMN system_notification_message.publisher_info IS '发布者信息';
COMMENT ON COLUMN system_notification_message.sent_channels IS '实际发送的渠道,参见 NotificationChannelEnum';
COMMENT ON COLUMN system_notification_message.read_status IS '是否已读';
COMMENT ON COLUMN system_notification_message.read_time IS '阅读时间';
COMMENT ON COLUMN system_notification_message.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_notification_message.id IS '主键 ID';
COMMENT ON COLUMN system_notification_message.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_notification_message.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_notification_message.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_notification_message.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_notification_message.deleted IS '是否已删除';


-- system_notification_notice：通知表
CREATE TABLE system_notification_notice (
	code VARCHAR(63), 
	builtin SMALLINT NOT NULL, 
	title VARCHAR(50) NOT NULL, 
	content TEXT NOT NULL, 
	type INTEGER NOT NULL, 
	user_type SMALLINT NOT NULL, 
	channels JSON NOT NULL, 
	sms_template_code VARCHAR(63), 
	mail_account_id BIGINT, 
	publisher VARCHAR(64) NOT NULL, 
	status SMALLINT NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_system_notification_notice_tenant ON system_notification_notice (tenant_id);
COMMENT ON TABLE system_notification_notice IS '通知表';
COMMENT ON COLUMN system_notification_notice.code IS '通知编码';
COMMENT ON COLUMN system_notification_notice.builtin IS '内置类型（1-内置 2-自定义）【BuiltinTypeEnum】';
COMMENT ON COLUMN system_notification_notice.title IS '通知标题';
COMMENT ON COLUMN system_notification_notice.content IS '通知内容';
COMMENT ON COLUMN system_notification_notice.type IS '通知类型【NoticeTypeEnum】';
COMMENT ON COLUMN system_notification_notice.user_type IS '用户类型【UserTypeEnum】';
COMMENT ON COLUMN system_notification_notice.channels IS '通知渠道,参见 NotificationChannelEnum';
COMMENT ON COLUMN system_notification_notice.sms_template_code IS '短信模板编码,选择SMS渠道时必填';
COMMENT ON COLUMN system_notification_notice.mail_account_id IS '邮箱账号编号,选择MAIL渠道时必填';
COMMENT ON COLUMN system_notification_notice.publisher IS '发布人';
COMMENT ON COLUMN system_notification_notice.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_notification_notice.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_notification_notice.id IS '主键 ID';
COMMENT ON COLUMN system_notification_notice.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_notification_notice.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_notification_notice.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_notification_notice.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_notification_notice.deleted IS '是否已删除';


-- system_notification_notice_log：通知日志表
CREATE TABLE system_notification_notice_log (
	notice_id BIGINT NOT NULL, 
	notice_title VARCHAR(100) NOT NULL, 
	notice_type INTEGER NOT NULL, 
	push_target_type SMALLINT NOT NULL, 
	target_user_ids JSON, 
	target_dept_ids JSON, 
	target_dept_names JSON, 
	push_channels JSON NOT NULL, 
	total_count INTEGER NOT NULL, 
	success_count INTEGER NOT NULL, 
	fail_count INTEGER NOT NULL, 
	push_status SMALLINT NOT NULL, 
	publisher_info JSON, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_system_notification_notice_log_tenant ON system_notification_notice_log (tenant_id);
COMMENT ON TABLE system_notification_notice_log IS '通知日志表';
COMMENT ON COLUMN system_notification_notice_log.notice_id IS '关联的通知编号';
COMMENT ON COLUMN system_notification_notice_log.notice_title IS '通知标题(冗余快照)';
COMMENT ON COLUMN system_notification_notice_log.notice_type IS '通知类型(冗余快照)';
COMMENT ON COLUMN system_notification_notice_log.push_target_type IS '推送目标类型(NoticePushTargetTypeEnum): 1=按用户, 2=按部门, 3=混合';
COMMENT ON COLUMN system_notification_notice_log.target_user_ids IS '目标用户ID列表(原始选择)';
COMMENT ON COLUMN system_notification_notice_log.target_dept_ids IS '目标部门ID列表(原始选择)';
COMMENT ON COLUMN system_notification_notice_log.target_dept_names IS '目标部门名称列表(冗余快照)';
COMMENT ON COLUMN system_notification_notice_log.push_channels IS '推送渠道';
COMMENT ON COLUMN system_notification_notice_log.total_count IS '推送总人数';
COMMENT ON COLUMN system_notification_notice_log.success_count IS '成功数';
COMMENT ON COLUMN system_notification_notice_log.fail_count IS '失败数';
COMMENT ON COLUMN system_notification_notice_log.push_status IS '推送状态(NoticePushStatusEnum): 0=推送中, 1=全部成功, 2=部分失败, 3=全部失败';
COMMENT ON COLUMN system_notification_notice_log.publisher_info IS '发布者信息';
COMMENT ON COLUMN system_notification_notice_log.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_notification_notice_log.id IS '主键 ID';
COMMENT ON COLUMN system_notification_notice_log.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_notification_notice_log.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_notification_notice_log.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_notification_notice_log.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_notification_notice_log.deleted IS '是否已删除';


-- system_oauth2_approve：OAuth2 批准表
CREATE TABLE system_oauth2_approve (
	user_id BIGINT NOT NULL, 
	user_type SMALLINT NOT NULL, 
	client_id VARCHAR(255) NOT NULL, 
	scope VARCHAR(255) NOT NULL, 
	approved BOOLEAN NOT NULL, 
	expires_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_system_oauth2_approve_tenant ON system_oauth2_approve (tenant_id);
COMMENT ON TABLE system_oauth2_approve IS 'OAuth2 批准表';
COMMENT ON COLUMN system_oauth2_approve.user_id IS '用户编号';
COMMENT ON COLUMN system_oauth2_approve.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_oauth2_approve.client_id IS '客户端编号';
COMMENT ON COLUMN system_oauth2_approve.scope IS '授权范围';
COMMENT ON COLUMN system_oauth2_approve.approved IS '是否接受';
COMMENT ON COLUMN system_oauth2_approve.expires_time IS '过期时间';
COMMENT ON COLUMN system_oauth2_approve.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_oauth2_approve.id IS '主键 ID';
COMMENT ON COLUMN system_oauth2_approve.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_oauth2_approve.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_oauth2_approve.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_oauth2_approve.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_oauth2_approve.deleted IS '是否已删除';


-- system_oauth2_client：OAuth2 客户端表
CREATE TABLE system_oauth2_client (
	client_id VARCHAR(255) NOT NULL, 
	secret VARCHAR(255) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	logo VARCHAR(255) NOT NULL, 
	description VARCHAR(255), 
	status SMALLINT NOT NULL, 
	user_type SMALLINT, 
	access_token_validity_seconds INTEGER NOT NULL, 
	refresh_token_validity_seconds INTEGER NOT NULL, 
	redirect_uris JSON NOT NULL, 
	authorized_grant_types JSON NOT NULL, 
	scopes JSON NOT NULL, 
	auto_approve_scopes JSON, 
	authorities JSON, 
	resource_ids JSON, 
	additional_information VARCHAR(255), 
	credential_revision INTEGER NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (client_id)
);
COMMENT ON TABLE system_oauth2_client IS 'OAuth2 客户端表';
COMMENT ON COLUMN system_oauth2_client.client_id IS '客户端编号';
COMMENT ON COLUMN system_oauth2_client.secret IS '客户端密钥';
COMMENT ON COLUMN system_oauth2_client.name IS '应用名';
COMMENT ON COLUMN system_oauth2_client.logo IS '应用图标';
COMMENT ON COLUMN system_oauth2_client.description IS '应用描述';
COMMENT ON COLUMN system_oauth2_client.status IS '状态';
COMMENT ON COLUMN system_oauth2_client.user_type IS '绑定的用户类型';
COMMENT ON COLUMN system_oauth2_client.access_token_validity_seconds IS '访问令牌的有效期';
COMMENT ON COLUMN system_oauth2_client.refresh_token_validity_seconds IS '刷新令牌的有效期';
COMMENT ON COLUMN system_oauth2_client.redirect_uris IS '可重定向的 URI 地址 (JSON 数组)';
COMMENT ON COLUMN system_oauth2_client.authorized_grant_types IS '授权类型 (JSON 数组)';
COMMENT ON COLUMN system_oauth2_client.scopes IS '授权范围 (JSON 数组)';
COMMENT ON COLUMN system_oauth2_client.auto_approve_scopes IS '自动通过的授权范围 (JSON 数组)';
COMMENT ON COLUMN system_oauth2_client.authorities IS '权限 (JSON 数组)';
COMMENT ON COLUMN system_oauth2_client.resource_ids IS '资源 (JSON 数组)';
COMMENT ON COLUMN system_oauth2_client.additional_information IS '附加信息';
COMMENT ON COLUMN system_oauth2_client.credential_revision IS '客户端凭据版本';
COMMENT ON COLUMN system_oauth2_client.id IS '主键 ID';
COMMENT ON COLUMN system_oauth2_client.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_oauth2_client.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_oauth2_client.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_oauth2_client.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_oauth2_client.deleted IS '是否已删除';


-- system_oauth2_code：OAuth2 授权码表
CREATE TABLE system_oauth2_code (
	user_id BIGINT NOT NULL, 
	user_type SMALLINT NOT NULL, 
	code_digest VARCHAR(64) NOT NULL, 
	client_id VARCHAR(255) NOT NULL, 
	scopes JSON, 
	expires_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	redirect_uri VARCHAR(255), 
	state VARCHAR(255) NOT NULL, 
	consumed BOOLEAN NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_oauth2_code_digest UNIQUE (tenant_id, code_digest)
);
CREATE INDEX ix_system_oauth2_code_tenant ON system_oauth2_code (tenant_id);
COMMENT ON TABLE system_oauth2_code IS 'OAuth2 授权码表';
COMMENT ON COLUMN system_oauth2_code.user_id IS '用户编号';
COMMENT ON COLUMN system_oauth2_code.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_oauth2_code.code_digest IS '授权码 SHA-256 摘要';
COMMENT ON COLUMN system_oauth2_code.client_id IS '客户端编号';
COMMENT ON COLUMN system_oauth2_code.scopes IS '授权范围 (JSON 数组)';
COMMENT ON COLUMN system_oauth2_code.expires_time IS '过期时间';
COMMENT ON COLUMN system_oauth2_code.redirect_uri IS '可重定向的 URI 地址';
COMMENT ON COLUMN system_oauth2_code.state IS '状态';
COMMENT ON COLUMN system_oauth2_code.consumed IS '授权码是否已消费';
COMMENT ON COLUMN system_oauth2_code.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_oauth2_code.id IS '主键 ID';
COMMENT ON COLUMN system_oauth2_code.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_oauth2_code.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_oauth2_code.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_oauth2_code.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_oauth2_code.deleted IS '是否已删除';


-- system_oauth2_refresh_token：OAuth2 刷新令牌
CREATE TABLE system_oauth2_refresh_token (
	user_id BIGINT NOT NULL, 
	token_digest VARCHAR(64) NOT NULL, 
	user_type SMALLINT NOT NULL, 
	client_id VARCHAR(255) NOT NULL, 
	scopes JSON, 
	expires_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	family_id VARCHAR(64) NOT NULL, 
	credential_revision INTEGER NOT NULL, 
	revoked BOOLEAN NOT NULL, 
	consumed_time TIMESTAMP WITHOUT TIME ZONE, 
	application_id VARCHAR(64) NOT NULL, 
	domain VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_oauth2_refresh_token_tenant_id UNIQUE (tenant_id, id), 
	CONSTRAINT uq_system_oauth2_refresh_token_digest UNIQUE (tenant_id, token_digest)
);
CREATE INDEX ix_system_oauth2_refresh_token_family ON system_oauth2_refresh_token (tenant_id, family_id);
CREATE INDEX ix_system_oauth2_refresh_token_lookup ON system_oauth2_refresh_token (application_id, domain, token_digest);
CREATE INDEX ix_system_oauth2_refresh_token_tenant ON system_oauth2_refresh_token (tenant_id);
COMMENT ON TABLE system_oauth2_refresh_token IS 'OAuth2 刷新令牌';
COMMENT ON COLUMN system_oauth2_refresh_token.user_id IS '用户编号';
COMMENT ON COLUMN system_oauth2_refresh_token.token_digest IS '刷新令牌 SHA-256 摘要';
COMMENT ON COLUMN system_oauth2_refresh_token.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_oauth2_refresh_token.client_id IS '客户端编号';
COMMENT ON COLUMN system_oauth2_refresh_token.scopes IS '授权范围 (存储为JSON)';
COMMENT ON COLUMN system_oauth2_refresh_token.expires_time IS '过期时间';
COMMENT ON COLUMN system_oauth2_refresh_token.family_id IS '会话族编号';
COMMENT ON COLUMN system_oauth2_refresh_token.credential_revision IS '签发时的凭据版本';
COMMENT ON COLUMN system_oauth2_refresh_token.revoked IS '是否撤销';
COMMENT ON COLUMN system_oauth2_refresh_token.consumed_time IS '轮换消费时间，保留记录用于重放检测';
COMMENT ON COLUMN system_oauth2_refresh_token.application_id IS '应用编号';
COMMENT ON COLUMN system_oauth2_refresh_token.domain IS '认证域';
COMMENT ON COLUMN system_oauth2_refresh_token.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_oauth2_refresh_token.id IS '主键 ID';
COMMENT ON COLUMN system_oauth2_refresh_token.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_oauth2_refresh_token.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_oauth2_refresh_token.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_oauth2_refresh_token.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_oauth2_refresh_token.deleted IS '是否已删除';


-- system_operate_log：操作日志记录
CREATE TABLE system_operate_log (
	trace_id VARCHAR(64) NOT NULL, 
	user_id BIGINT NOT NULL, 
	user_type SMALLINT NOT NULL, 
	type VARCHAR(50) NOT NULL, 
	sub_type VARCHAR(50) NOT NULL, 
	biz_id BIGINT NOT NULL, 
	action TEXT NOT NULL, 
	extra TEXT NOT NULL, 
	request_method VARCHAR(16) NOT NULL, 
	request_url VARCHAR(255) NOT NULL, 
	user_ip VARCHAR(50) NOT NULL, 
	user_agent VARCHAR(200) NOT NULL, 
	user_info JSON NOT NULL, 
	event_id VARCHAR(32), 
	result VARCHAR(16), 
	duration_ms FLOAT, 
	lease_until TIMESTAMP WITHOUT TIME ZONE, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_system_operate_log_tenant ON system_operate_log (tenant_id);
COMMENT ON TABLE system_operate_log IS '操作日志记录';
COMMENT ON COLUMN system_operate_log.trace_id IS '链路追踪编号';
COMMENT ON COLUMN system_operate_log.user_id IS '用户编号';
COMMENT ON COLUMN system_operate_log.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_operate_log.type IS '操作模块类型';
COMMENT ON COLUMN system_operate_log.sub_type IS '操作名';
COMMENT ON COLUMN system_operate_log.biz_id IS '操作数据模块编号';
COMMENT ON COLUMN system_operate_log.action IS '操作内容';
COMMENT ON COLUMN system_operate_log.extra IS '拓展字段';
COMMENT ON COLUMN system_operate_log.request_method IS '请求方法名';
COMMENT ON COLUMN system_operate_log.request_url IS '请求地址';
COMMENT ON COLUMN system_operate_log.user_ip IS '用户 IP';
COMMENT ON COLUMN system_operate_log.user_agent IS '浏览器 UA';
COMMENT ON COLUMN system_operate_log.user_info IS '用户信息 (JSON 格式)';
COMMENT ON COLUMN system_operate_log.event_id IS '审计预留编号';
COMMENT ON COLUMN system_operate_log.result IS 'pending/success/failure/cancelled';
COMMENT ON COLUMN system_operate_log.duration_ms IS '操作耗时毫秒';
COMMENT ON COLUMN system_operate_log.lease_until IS '审计预留有效期';
COMMENT ON COLUMN system_operate_log.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_operate_log.id IS '主键 ID';
COMMENT ON COLUMN system_operate_log.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_operate_log.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_operate_log.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_operate_log.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_operate_log.deleted IS '是否已删除';


-- system_post：岗位信息表
CREATE TABLE system_post (
	code VARCHAR(64) NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	sort INTEGER NOT NULL, 
	status SMALLINT NOT NULL, 
	remark VARCHAR(500), 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_post_active_0 UNIQUE (tenant_id, code, active_key), 
	CONSTRAINT uq_system_post_tenant_id UNIQUE (tenant_id, id)
);
CREATE INDEX ix_system_post_tenant ON system_post (tenant_id);
COMMENT ON TABLE system_post IS '岗位信息表';
COMMENT ON COLUMN system_post.code IS '岗位编码';
COMMENT ON COLUMN system_post.name IS '岗位名称';
COMMENT ON COLUMN system_post.sort IS '显示顺序';
COMMENT ON COLUMN system_post.status IS '开启状态（1-启用，0-禁用）【StatusEnum】';
COMMENT ON COLUMN system_post.remark IS '备注';
COMMENT ON COLUMN system_post.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_post.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_post.id IS '主键 ID';
COMMENT ON COLUMN system_post.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_post.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_post.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_post.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_post.deleted IS '是否已删除';


-- system_role：角色信息表
CREATE TABLE system_role (
	name VARCHAR(30) NOT NULL, 
	code VARCHAR(100) NOT NULL, 
	sort INTEGER NOT NULL, 
	data_scope SMALLINT NOT NULL, 
	data_scope_dept_ids JSON NOT NULL, 
	builtin SMALLINT NOT NULL, 
	status SMALLINT NOT NULL, 
	remark VARCHAR(500), 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_role_active_0 UNIQUE (tenant_id, code, active_key), 
	CONSTRAINT uq_system_role_tenant_id UNIQUE (tenant_id, id)
);
CREATE INDEX ix_system_role_tenant ON system_role (tenant_id);
COMMENT ON TABLE system_role IS '角色信息表';
COMMENT ON COLUMN system_role.name IS '角色名称';
COMMENT ON COLUMN system_role.code IS '角色权限字符串';
COMMENT ON COLUMN system_role.sort IS '显示顺序';
COMMENT ON COLUMN system_role.data_scope IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限 5：本人数据）';
COMMENT ON COLUMN system_role.data_scope_dept_ids IS '数据范围(指定部门数组)';
COMMENT ON COLUMN system_role.builtin IS '内置类型（1-内置 2-自定义）【BuiltinTypeEnum】';
COMMENT ON COLUMN system_role.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_role.remark IS '备注';
COMMENT ON COLUMN system_role.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_role.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_role.id IS '主键 ID';
COMMENT ON COLUMN system_role.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_role.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_role.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_role.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_role.deleted IS '是否已删除';


-- system_sms_channel：短信渠道信息表
CREATE TABLE system_sms_channel (
	signature VARCHAR(12) NOT NULL, 
	code VARCHAR(63) NOT NULL, 
	status SMALLINT NOT NULL, 
	remark VARCHAR(255), 
	api_key VARCHAR(128) NOT NULL, 
	api_secret VARCHAR(128), 
	callback_url VARCHAR(255), 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_sms_channel_tenant_id UNIQUE (tenant_id, id)
);
CREATE INDEX ix_system_sms_channel_tenant ON system_sms_channel (tenant_id);
COMMENT ON TABLE system_sms_channel IS '短信渠道信息表';
COMMENT ON COLUMN system_sms_channel.signature IS '短信签名';
COMMENT ON COLUMN system_sms_channel.code IS '渠道编码【SmsChannelEnum】';
COMMENT ON COLUMN system_sms_channel.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_sms_channel.remark IS '备注';
COMMENT ON COLUMN system_sms_channel.api_key IS '短信 API 的账号';
COMMENT ON COLUMN system_sms_channel.api_secret IS '短信 API 的秘钥';
COMMENT ON COLUMN system_sms_channel.callback_url IS '短信发送回调 URL';
COMMENT ON COLUMN system_sms_channel.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_sms_channel.id IS '主键 ID';
COMMENT ON COLUMN system_sms_channel.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_sms_channel.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_sms_channel.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_sms_channel.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_sms_channel.deleted IS '是否已删除';


-- system_sms_code：手机验证码表
CREATE TABLE system_sms_code (
	mobile VARCHAR(11) NOT NULL, 
	code VARCHAR(6) NOT NULL, 
	create_ip VARCHAR(15) NOT NULL, 
	scene SMALLINT NOT NULL, 
	today_index SMALLINT NOT NULL, 
	used BOOLEAN NOT NULL, 
	used_time TIMESTAMP WITHOUT TIME ZONE, 
	used_ip VARCHAR(255), 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_system_sms_code_tenant ON system_sms_code (tenant_id);
COMMENT ON TABLE system_sms_code IS '手机验证码表';
COMMENT ON COLUMN system_sms_code.mobile IS '手机号';
COMMENT ON COLUMN system_sms_code.code IS '验证码';
COMMENT ON COLUMN system_sms_code.create_ip IS '创建 IP';
COMMENT ON COLUMN system_sms_code.scene IS '发送场景';
COMMENT ON COLUMN system_sms_code.today_index IS '今日发送的第几条';
COMMENT ON COLUMN system_sms_code.used IS '是否使用';
COMMENT ON COLUMN system_sms_code.used_time IS '使用时间';
COMMENT ON COLUMN system_sms_code.used_ip IS '使用 IP';
COMMENT ON COLUMN system_sms_code.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_sms_code.id IS '主键 ID';
COMMENT ON COLUMN system_sms_code.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_sms_code.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_sms_code.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_sms_code.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_sms_code.deleted IS '是否已删除';


-- system_sms_log：短信日志表
CREATE TABLE system_sms_log (
	channel_id BIGINT NOT NULL, 
	channel_code VARCHAR(63) NOT NULL, 
	template_id BIGINT NOT NULL, 
	template_code VARCHAR(63) NOT NULL, 
	template_type SMALLINT NOT NULL, 
	template_content VARCHAR(255) NOT NULL, 
	template_params JSON NOT NULL, 
	api_template_id VARCHAR(63), 
	mobile VARCHAR(11) NOT NULL, 
	user_id BIGINT, 
	user_type SMALLINT NOT NULL, 
	send_status SMALLINT NOT NULL, 
	send_time TIMESTAMP WITHOUT TIME ZONE, 
	api_send_code VARCHAR(63), 
	api_send_msg VARCHAR(255), 
	api_request_id VARCHAR(255), 
	api_serial_no VARCHAR(255), 
	receive_status SMALLINT NOT NULL, 
	receive_time TIMESTAMP WITHOUT TIME ZONE, 
	api_receive_code VARCHAR(63), 
	api_receive_msg VARCHAR(255), 
	send_claim_token VARCHAR(32), 
	send_claim_until TIMESTAMP WITHOUT TIME ZONE, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_system_sms_log_tenant ON system_sms_log (tenant_id);
COMMENT ON TABLE system_sms_log IS '短信日志表';
COMMENT ON COLUMN system_sms_log.channel_id IS '短信渠道编号';
COMMENT ON COLUMN system_sms_log.channel_code IS '短信渠道编码';
COMMENT ON COLUMN system_sms_log.template_id IS '模板编号';
COMMENT ON COLUMN system_sms_log.template_code IS '模板编码';
COMMENT ON COLUMN system_sms_log.template_type IS '短信类型【SmsTemplateTypeEnum】';
COMMENT ON COLUMN system_sms_log.template_content IS '短信内容';
COMMENT ON COLUMN system_sms_log.template_params IS '短信参数';
COMMENT ON COLUMN system_sms_log.api_template_id IS '短信 API 的模板编号';
COMMENT ON COLUMN system_sms_log.mobile IS '手机号';
COMMENT ON COLUMN system_sms_log.user_id IS '用户编号';
COMMENT ON COLUMN system_sms_log.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_sms_log.send_status IS '发送状态';
COMMENT ON COLUMN system_sms_log.send_time IS '发送时间';
COMMENT ON COLUMN system_sms_log.api_send_code IS '短信 API 发送结果的编码';
COMMENT ON COLUMN system_sms_log.api_send_msg IS '短信 API 发送失败的提示';
COMMENT ON COLUMN system_sms_log.api_request_id IS '短信 API 发送返回的唯一请求 ID';
COMMENT ON COLUMN system_sms_log.api_serial_no IS '短信 API 发送返回的序号';
COMMENT ON COLUMN system_sms_log.receive_status IS '接收状态';
COMMENT ON COLUMN system_sms_log.receive_time IS '接收时间';
COMMENT ON COLUMN system_sms_log.api_receive_code IS 'API 接收结果的编码';
COMMENT ON COLUMN system_sms_log.api_receive_msg IS 'API 接收结果的说明';
COMMENT ON COLUMN system_sms_log.send_claim_token IS '外发 claim 令牌';
COMMENT ON COLUMN system_sms_log.send_claim_until IS '外发前 claim 到期时间';
COMMENT ON COLUMN system_sms_log.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_sms_log.id IS '主键 ID';
COMMENT ON COLUMN system_sms_log.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_sms_log.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_sms_log.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_sms_log.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_sms_log.deleted IS '是否已删除';


-- system_social_client：社交客户端表
CREATE TABLE system_social_client (
	name VARCHAR(255) NOT NULL, 
	social_type SMALLINT NOT NULL, 
	user_type SMALLINT NOT NULL, 
	client_id VARCHAR(255) NOT NULL, 
	client_secret TEXT NOT NULL, 
	agent_id VARCHAR(255), 
	auth_config JSON DEFAULT '{}' NOT NULL, 
	status SMALLINT NOT NULL, 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_social_client_active_0 UNIQUE (tenant_id, social_type, user_type, active_key)
);
CREATE INDEX ix_system_social_client_tenant ON system_social_client (tenant_id);
COMMENT ON TABLE system_social_client IS '社交客户端表';
COMMENT ON COLUMN system_social_client.name IS '应用名';
COMMENT ON COLUMN system_social_client.social_type IS '社交平台的类型【SocialTypeEnum】';
COMMENT ON COLUMN system_social_client.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_social_client.client_id IS '客户端编号';
COMMENT ON COLUMN system_social_client.client_secret IS '客户端密钥，支付宝等渠道存放 PEM 私钥';
COMMENT ON COLUMN system_social_client.agent_id IS '代理编号';
COMMENT ON COLUMN system_social_client.auth_config IS '认证配置，JSON格式';
COMMENT ON COLUMN system_social_client.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_social_client.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_social_client.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_social_client.id IS '主键 ID';
COMMENT ON COLUMN system_social_client.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_social_client.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_social_client.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_social_client.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_social_client.deleted IS '是否已删除';


-- system_social_user：社交用户表
CREATE TABLE system_social_user (
	type SMALLINT NOT NULL, 
	openid VARCHAR(32) NOT NULL, 
	token VARCHAR(256), 
	raw_token_info TEXT NOT NULL, 
	nickname VARCHAR(32) NOT NULL, 
	avatar VARCHAR(255), 
	raw_user_info TEXT NOT NULL, 
	code VARCHAR(256) NOT NULL, 
	state VARCHAR(256), 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	client_id VARCHAR(255) NOT NULL, 
	subject_type VARCHAR(32) NOT NULL, 
	application_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_social_user_active_0 UNIQUE (tenant_id, type, openid, client_id, subject_type, application_id, active_key), 
	CONSTRAINT uq_system_social_user_tenant_id UNIQUE (tenant_id, id)
);
CREATE INDEX ix_system_social_user_tenant ON system_social_user (tenant_id);
COMMENT ON TABLE system_social_user IS '社交用户表';
COMMENT ON COLUMN system_social_user.type IS '社交平台的类型【SocialTypeEnum】';
COMMENT ON COLUMN system_social_user.openid IS '社交 openid';
COMMENT ON COLUMN system_social_user.token IS '社交 token';
COMMENT ON COLUMN system_social_user.raw_token_info IS '原始 Token 数据，一般是 JSON 格式';
COMMENT ON COLUMN system_social_user.nickname IS '用户昵称';
COMMENT ON COLUMN system_social_user.avatar IS '用户头像';
COMMENT ON COLUMN system_social_user.raw_user_info IS '原始用户数据，一般是 JSON 格式';
COMMENT ON COLUMN system_social_user.code IS '最后一次的认证 code';
COMMENT ON COLUMN system_social_user.state IS '最后一次的认证 state';
COMMENT ON COLUMN system_social_user.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_social_user.client_id IS '第三方应用编号';
COMMENT ON COLUMN system_social_user.subject_type IS '第三方主体类型';
COMMENT ON COLUMN system_social_user.application_id IS '本站社交应用标识';
COMMENT ON COLUMN system_social_user.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_social_user.id IS '主键 ID';
COMMENT ON COLUMN system_social_user.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_social_user.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_social_user.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_social_user.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_social_user.deleted IS '是否已删除';


-- system_tenant：租户
CREATE TABLE system_tenant (
	name VARCHAR(30) NOT NULL, 
	contact_user_id BIGINT, 
	contact_name VARCHAR(30) NOT NULL, 
	contact_mobile VARCHAR(50), 
	status SMALLINT NOT NULL, 
	websites JSON, 
	package_id BIGINT NOT NULL, 
	expire_time TIMESTAMP WITHOUT TIME ZONE, 
	account_count BIGINT NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
COMMENT ON TABLE system_tenant IS '租户';
COMMENT ON COLUMN system_tenant.name IS '租户名';
COMMENT ON COLUMN system_tenant.contact_user_id IS '联系人的用户编号';
COMMENT ON COLUMN system_tenant.contact_name IS '联系人';
COMMENT ON COLUMN system_tenant.contact_mobile IS '联系手机';
COMMENT ON COLUMN system_tenant.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_tenant.websites IS '绑定域名列表';
COMMENT ON COLUMN system_tenant.package_id IS '租户套餐编号';
COMMENT ON COLUMN system_tenant.expire_time IS '过期时间';
COMMENT ON COLUMN system_tenant.account_count IS '账号数量';
COMMENT ON COLUMN system_tenant.id IS '主键 ID';
COMMENT ON COLUMN system_tenant.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_tenant.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_tenant.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_tenant.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_tenant.deleted IS '是否已删除';


-- system_tenant_package：租户套餐
CREATE TABLE system_tenant_package (
	name VARCHAR(30) NOT NULL, 
	status SMALLINT NOT NULL, 
	remark VARCHAR(256), 
	menu_ids JSON NOT NULL, 
	quota_config JSON, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
COMMENT ON TABLE system_tenant_package IS '租户套餐';
COMMENT ON COLUMN system_tenant_package.name IS '套餐名';
COMMENT ON COLUMN system_tenant_package.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_tenant_package.remark IS '备注';
COMMENT ON COLUMN system_tenant_package.menu_ids IS '关联的菜单编号 (JSON)';
COMMENT ON COLUMN system_tenant_package.quota_config IS '通用配额模板（多模块共享，如 ai / sms / storage）';
COMMENT ON COLUMN system_tenant_package.id IS '主键 ID';
COMMENT ON COLUMN system_tenant_package.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_tenant_package.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_tenant_package.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_tenant_package.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_tenant_package.deleted IS '是否已删除';


-- system_oauth2_access_token：OAuth2 访问令牌
CREATE TABLE system_oauth2_access_token (
	user_id BIGINT NOT NULL, 
	user_type SMALLINT NOT NULL, 
	user_info JSON NOT NULL, 
	scopes JSON, 
	token_digest VARCHAR(64) NOT NULL, 
	refresh_token_id BIGINT, 
	client_id VARCHAR(255) NOT NULL, 
	expires_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	family_id VARCHAR(64) NOT NULL, 
	credential_revision INTEGER NOT NULL, 
	revoked BOOLEAN NOT NULL, 
	application_id VARCHAR(64) NOT NULL, 
	domain VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT fk_system_oauth2_access_token_refresh_token_id FOREIGN KEY(tenant_id, refresh_token_id) REFERENCES system_oauth2_refresh_token (tenant_id, id), 
	CONSTRAINT uq_system_oauth2_access_token_digest UNIQUE (tenant_id, token_digest)
);
CREATE INDEX ix_system_oauth2_access_token_family ON system_oauth2_access_token (tenant_id, family_id);
CREATE INDEX ix_system_oauth2_access_token_lookup ON system_oauth2_access_token (application_id, domain, token_digest);
CREATE INDEX ix_system_oauth2_access_token_tenant ON system_oauth2_access_token (tenant_id);
COMMENT ON TABLE system_oauth2_access_token IS 'OAuth2 访问令牌';
COMMENT ON COLUMN system_oauth2_access_token.user_id IS '用户编号';
COMMENT ON COLUMN system_oauth2_access_token.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_oauth2_access_token.user_info IS '用户信息 (JSON 格式)';
COMMENT ON COLUMN system_oauth2_access_token.scopes IS '授权范围 (JSON 数组格式)';
COMMENT ON COLUMN system_oauth2_access_token.token_digest IS '访问令牌 SHA-256 摘要';
COMMENT ON COLUMN system_oauth2_access_token.refresh_token_id IS '刷新令牌记录编号';
COMMENT ON COLUMN system_oauth2_access_token.client_id IS '客户端编号';
COMMENT ON COLUMN system_oauth2_access_token.expires_time IS '过期时间';
COMMENT ON COLUMN system_oauth2_access_token.family_id IS '会话族编号';
COMMENT ON COLUMN system_oauth2_access_token.credential_revision IS '签发时的凭据版本';
COMMENT ON COLUMN system_oauth2_access_token.revoked IS '是否撤销';
COMMENT ON COLUMN system_oauth2_access_token.application_id IS '应用编号';
COMMENT ON COLUMN system_oauth2_access_token.domain IS '认证域';
COMMENT ON COLUMN system_oauth2_access_token.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_oauth2_access_token.id IS '主键 ID';
COMMENT ON COLUMN system_oauth2_access_token.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_oauth2_access_token.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_oauth2_access_token.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_oauth2_access_token.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_oauth2_access_token.deleted IS '是否已删除';


-- system_role_menu：角色和菜单关联表
CREATE TABLE system_role_menu (
	role_id BIGINT NOT NULL, 
	menu_id BIGINT NOT NULL, 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_role_menu_active_0 UNIQUE (tenant_id, role_id, menu_id, active_key), 
	CONSTRAINT fk_system_role_menu_role_id FOREIGN KEY(tenant_id, role_id) REFERENCES system_role (tenant_id, id)
);
CREATE INDEX ix_system_role_menu_tenant ON system_role_menu (tenant_id);
COMMENT ON TABLE system_role_menu IS '角色和菜单关联表';
COMMENT ON COLUMN system_role_menu.role_id IS '角色ID';
COMMENT ON COLUMN system_role_menu.menu_id IS '菜单ID';
COMMENT ON COLUMN system_role_menu.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_role_menu.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_role_menu.id IS '主键 ID';
COMMENT ON COLUMN system_role_menu.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_role_menu.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_role_menu.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_role_menu.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_role_menu.deleted IS '是否已删除';


-- system_sms_template：短信模板表
CREATE TABLE system_sms_template (
	type SMALLINT NOT NULL, 
	builtin SMALLINT NOT NULL, 
	status SMALLINT NOT NULL, 
	code VARCHAR(63) NOT NULL, 
	name VARCHAR(63) NOT NULL, 
	content VARCHAR(255) NOT NULL, 
	params JSON NOT NULL, 
	remark VARCHAR(255), 
	api_template_id VARCHAR(63) NOT NULL, 
	channel_id BIGINT NOT NULL, 
	channel_code VARCHAR(63) NOT NULL, 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_sms_template_active_0 UNIQUE (tenant_id, code, active_key), 
	CONSTRAINT fk_system_sms_template_channel_id FOREIGN KEY(tenant_id, channel_id) REFERENCES system_sms_channel (tenant_id, id)
);
CREATE INDEX ix_system_sms_template_tenant ON system_sms_template (tenant_id);
COMMENT ON TABLE system_sms_template IS '短信模板表';
COMMENT ON COLUMN system_sms_template.type IS '短信类型【SmsTemplateTypeEnum】';
COMMENT ON COLUMN system_sms_template.builtin IS '内置类型（1-内置 2-自定义）【BuiltinTypeEnum】';
COMMENT ON COLUMN system_sms_template.status IS '开启状态（1-启用，0-禁用）【StatusEnum】';
COMMENT ON COLUMN system_sms_template.code IS '模板编码';
COMMENT ON COLUMN system_sms_template.name IS '模板名称';
COMMENT ON COLUMN system_sms_template.content IS '模板内容';
COMMENT ON COLUMN system_sms_template.params IS '参数数组';
COMMENT ON COLUMN system_sms_template.remark IS '备注';
COMMENT ON COLUMN system_sms_template.api_template_id IS '短信 API 的模板编号';
COMMENT ON COLUMN system_sms_template.channel_id IS '短信渠道编号';
COMMENT ON COLUMN system_sms_template.channel_code IS '短信渠道编码';
COMMENT ON COLUMN system_sms_template.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_sms_template.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_sms_template.id IS '主键 ID';
COMMENT ON COLUMN system_sms_template.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_sms_template.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_sms_template.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_sms_template.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_sms_template.deleted IS '是否已删除';


-- system_social_user_bind：社交绑定表
CREATE TABLE system_social_user_bind (
	user_id BIGINT NOT NULL, 
	user_type SMALLINT NOT NULL, 
	social_type SMALLINT NOT NULL, 
	social_user_id BIGINT NOT NULL, 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_social_user_bind_active_0 UNIQUE (tenant_id, user_type, social_type, social_user_id, active_key), 
	CONSTRAINT uq_system_social_user_bind_active_1 UNIQUE (tenant_id, user_type, social_type, user_id, active_key), 
	CONSTRAINT fk_system_social_user_bind_social_user_id FOREIGN KEY(tenant_id, social_user_id) REFERENCES system_social_user (tenant_id, id)
);
CREATE INDEX ix_system_social_user_bind_tenant ON system_social_user_bind (tenant_id);
COMMENT ON TABLE system_social_user_bind IS '社交绑定表';
COMMENT ON COLUMN system_social_user_bind.user_id IS '用户编号';
COMMENT ON COLUMN system_social_user_bind.user_type IS '用户类型（枚举）【UserTypeEnum】';
COMMENT ON COLUMN system_social_user_bind.social_type IS '社交平台的类型【SocialTypeEnum】';
COMMENT ON COLUMN system_social_user_bind.social_user_id IS '社交用户的编号';
COMMENT ON COLUMN system_social_user_bind.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_social_user_bind.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_social_user_bind.id IS '主键 ID';
COMMENT ON COLUMN system_social_user_bind.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_social_user_bind.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_social_user_bind.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_social_user_bind.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_social_user_bind.deleted IS '是否已删除';


-- system_users：用户信息表
CREATE TABLE system_users (
	username VARCHAR(30) NOT NULL, 
	password VARCHAR(100) NOT NULL, 
	nickname VARCHAR(30), 
	remark VARCHAR(500), 
	dept_id BIGINT, 
	post_ids JSON, 
	email VARCHAR(50), 
	mobile VARCHAR(11), 
	sex SMALLINT, 
	avatar VARCHAR(512), 
	status SMALLINT NOT NULL, 
	login_ip VARCHAR(50), 
	login_date TIMESTAMP WITHOUT TIME ZONE, 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	credential_revision INTEGER NOT NULL, 
	authorization_revision INTEGER NOT NULL, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_users_active_0 UNIQUE (tenant_id, username, active_key), 
	CONSTRAINT uq_system_users_tenant_id UNIQUE (tenant_id, id), 
	CONSTRAINT fk_system_users_dept_id FOREIGN KEY(tenant_id, dept_id) REFERENCES system_dept (tenant_id, id)
);
CREATE INDEX ix_system_users_tenant ON system_users (tenant_id);
COMMENT ON TABLE system_users IS '用户信息表';
COMMENT ON COLUMN system_users.username IS '用户账号';
COMMENT ON COLUMN system_users.password IS '密码';
COMMENT ON COLUMN system_users.nickname IS '用户昵称';
COMMENT ON COLUMN system_users.remark IS '备注';
COMMENT ON COLUMN system_users.dept_id IS '部门ID';
COMMENT ON COLUMN system_users.post_ids IS '岗位编号列表（JSON 格式）';
COMMENT ON COLUMN system_users.email IS '用户邮箱';
COMMENT ON COLUMN system_users.mobile IS '手机号码';
COMMENT ON COLUMN system_users.sex IS '用户性别';
COMMENT ON COLUMN system_users.avatar IS '头像地址';
COMMENT ON COLUMN system_users.status IS '开启状态（1-启用，0-禁用）';
COMMENT ON COLUMN system_users.login_ip IS '最后登录IP';
COMMENT ON COLUMN system_users.login_date IS '最后登录时间';
COMMENT ON COLUMN system_users.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_users.credential_revision IS '凭据版本，改密或账号状态变化时递增';
COMMENT ON COLUMN system_users.authorization_revision IS '权限版本，与授权变化原子提交';
COMMENT ON COLUMN system_users.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_users.id IS '主键 ID';
COMMENT ON COLUMN system_users.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_users.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_users.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_users.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_users.deleted IS '是否已删除';


-- system_user_post：用户岗位表
CREATE TABLE system_user_post (
	user_id BIGINT NOT NULL, 
	post_id BIGINT NOT NULL, 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_user_post_active_0 UNIQUE (tenant_id, user_id, post_id, active_key), 
	CONSTRAINT fk_system_user_post_user_id FOREIGN KEY(tenant_id, user_id) REFERENCES system_users (tenant_id, id), 
	CONSTRAINT fk_system_user_post_post_id FOREIGN KEY(tenant_id, post_id) REFERENCES system_post (tenant_id, id)
);
CREATE INDEX ix_system_user_post_tenant ON system_user_post (tenant_id);
COMMENT ON TABLE system_user_post IS '用户岗位表';
COMMENT ON COLUMN system_user_post.user_id IS '用户ID';
COMMENT ON COLUMN system_user_post.post_id IS '岗位ID';
COMMENT ON COLUMN system_user_post.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_user_post.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_user_post.id IS '主键 ID';
COMMENT ON COLUMN system_user_post.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_user_post.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_user_post.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_user_post.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_user_post.deleted IS '是否已删除';


-- system_user_profiles：用户详情表
CREATE TABLE system_user_profiles (
	user_id BIGINT NOT NULL, 
	bio VARCHAR(500), 
	tags JSON, 
	address VARCHAR(255), 
	skills JSON, 
	work_scope VARCHAR(500), 
	expertise VARCHAR(500), 
	communication_style VARCHAR(50), 
	ai_preference JSON, 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_user_profiles_active_0 UNIQUE (tenant_id, user_id, active_key), 
	CONSTRAINT fk_system_user_profiles_user_id FOREIGN KEY(tenant_id, user_id) REFERENCES system_users (tenant_id, id)
);
CREATE INDEX ix_system_user_profiles_tenant ON system_user_profiles (tenant_id);
CREATE INDEX ix_system_user_profiles_user_id ON system_user_profiles (user_id);
COMMENT ON TABLE system_user_profiles IS '用户详情表';
COMMENT ON COLUMN system_user_profiles.user_id IS '用户ID';
COMMENT ON COLUMN system_user_profiles.bio IS '个人简介';
COMMENT ON COLUMN system_user_profiles.tags IS '用户标签';
COMMENT ON COLUMN system_user_profiles.address IS '地址';
COMMENT ON COLUMN system_user_profiles.skills IS '技能标签';
COMMENT ON COLUMN system_user_profiles.work_scope IS '工作职责描述';
COMMENT ON COLUMN system_user_profiles.expertise IS '专业领域';
COMMENT ON COLUMN system_user_profiles.communication_style IS '沟通风格（formal/casual/technical）';
COMMENT ON COLUMN system_user_profiles.ai_preference IS 'AI 交互偏好（用户主动设置）';
COMMENT ON COLUMN system_user_profiles.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_user_profiles.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_user_profiles.id IS '主键 ID';
COMMENT ON COLUMN system_user_profiles.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_user_profiles.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_user_profiles.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_user_profiles.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_user_profiles.deleted IS '是否已删除';


-- system_user_role：用户角色关联表
CREATE TABLE system_user_role (
	user_id BIGINT NOT NULL, 
	role_id BIGINT NOT NULL, 
	active_key SMALLINT GENERATED ALWAYS AS (CASE WHEN (deleted = false) THEN 1 ELSE NULL END) STORED, 
	tenant_id VARCHAR(32) NOT NULL, 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	creator VARCHAR(64) NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updater VARCHAR(64) NOT NULL, 
	update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_system_user_role_active_0 UNIQUE (tenant_id, user_id, role_id, active_key), 
	CONSTRAINT fk_system_user_role_user_id FOREIGN KEY(tenant_id, user_id) REFERENCES system_users (tenant_id, id), 
	CONSTRAINT fk_system_user_role_role_id FOREIGN KEY(tenant_id, role_id) REFERENCES system_role (tenant_id, id)
);
CREATE INDEX ix_system_user_role_tenant ON system_user_role (tenant_id);
COMMENT ON TABLE system_user_role IS '用户角色关联表';
COMMENT ON COLUMN system_user_role.user_id IS '用户ID';
COMMENT ON COLUMN system_user_role.role_id IS '角色ID';
COMMENT ON COLUMN system_user_role.active_key IS '仅有效记录参与业务唯一约束';
COMMENT ON COLUMN system_user_role.tenant_id IS '租户 ID（租户主键的字符串形式）';
COMMENT ON COLUMN system_user_role.id IS '主键 ID';
COMMENT ON COLUMN system_user_role.creator IS '创建者账号 ID';
COMMENT ON COLUMN system_user_role.create_time IS '创建时间（UTC）';
COMMENT ON COLUMN system_user_role.updater IS '更新者账号 ID';
COMMENT ON COLUMN system_user_role.update_time IS '更新时间（UTC）';
COMMENT ON COLUMN system_user_role.deleted IS '是否已删除';
